name: Create Terraform Cloud Team

on:
  push:
    branches:
      - main

jobs:
  create-terraform-cloud-team:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Create Team
        
        run: |
          ./creationTeam.sh
