name: Create Terraform Cloud Team and workspace with input

on:
  workflow_dispatch:
    inputs:
      team_name:
        description: 'Team name'
        required: true
      workspace_name:
        description: 'Worksapce name'
        required: true


jobs:
  create-terraform-cloud-team-worksapce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Create Team 
        
        run: | 
           chmod +x ./TFCloudCurls/creationTeam.sh
           team_id=$(./TFCloudCurls/creationTeam.sh "${{ github.event.inputs.team_name }}" "${{ secrets.TF_API_TOKEN }}" | jq -r '.data.id')
           
           
           echo "TEAM_ID=$team_id" >> $GITHUB_ENV
      - name: Create  Workspace
        
        run: | 
             chmod +x ./TFCloudCurls/creationWS.sh
             workspace_id=$(./TFCloudCurls/creationWS.sh "${{ github.event.inputs.workspace_name }}" "${{ secrets.TF_API_TOKEN }}" | jq -r '.data.id')
   
             
             echo "WORKSPACE_ID=$workspace_id" >> $GITHUB_ENV

      - name: Create Relation 
        
        run: | 
                 chmod +x ./TFCloudCurls/createRelation.sh
                 ./TFCloudCurls/creationWS.sh  "${{ secrets.TF_API_TOKEN }}"
   
             
        
    
