name: Create Terraform Cloud Team and workspace with input

on:
  workflow_dispatch:
    inputs:
      team_name:
        description: 'Team name'
        required: true
      worksapce_name:
        description: 'Worksapce name'
        required: true


jobs:
  create-terraform-cloud-team-worksapce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Create  Workspace
        
        run: | 
          chmod +x ./TFCloudCurls/creationWS.sh
          ./TFCloudCurls/creationWS.sh  ${{ secrets.TF_API_TOKEN }} 

      - name: Create Team 
        
        run: | 
           chmod +x ./TFCloudCurls/creationTeam.sh
           ./TFCloudCurls/creationTeam.sh  "${{ github.event.inputs.team_name }}" ${{ secrets.TF_API_TOKEN }}
    
    
